# Generated by Django 5.1.7 on 2025-03-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='receipt_type',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver')], default='gold', max_length=10),
        ),
    ]
